version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql

    restart: always
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
        - db